services:
  - type: web
    name: npat-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        generateValue: false
        value: 10000
      - key: NODE_ENV
        value: production
